[project]
name = "financialtradingwithpython"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bt>=1.2.0",
    "jupyterlab>=4.6.2",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "plotly>=6.9.0",
    "ta-lib>=0.7.1",
]
